version: '3'

services:
  db_postgres:
    container_name: 'db_postgres'
    image: postgres:13.0-alpine
    restart: unless-stopped
    volumes:
      - ./db_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    env_file:
      - ./config/postgres.env
